### ISSUE TITLE
Result and State are mixed up

### ISSUE THREAD

**Issue by totalwarANGEL1993** [Siedelwood/Revision#10]
**Describe the bug**
in the method "ModuleQuest.Global:ProcessChatInput" and it's helpers the result and the state of a quest are mixed up and used synonymous which is wrong and will not produce the intended result.

**To Reproduce**
Just look in the file qsb\lua\modules\QSB_2_Quest\source.lua at line 646. QuestResult.NotTriggered does not exist while a QuestState.NotTriggered does. This means that the method wich is supposed to find quests with the passed result will never find a quest that is not triggered. The same goes for QuestResult.Active which also does not exist and QuestState.Active was probably intended.

**Comment by totalwarANGEL1993** [comment]
Ach so ja, ich dachte, das soll Englisch, weil Template Englisch. ^^

**Comment by Jelumar** [comment]
Vielen Dank für den Hinweis @totalwarANGEL1993 
Habe das angepasst und jetzt wird der QuestState verwendet.
