### ISSUE TITLE
Skriptnamenverlusst bei Verwendung eines Replacement

### ISSUE THREAD

**Issue by totalwarANGEL1993** [Siedelwood/Revision#11]
Wird ein Replacement bei einem interaktiven Objekt gesetzt, dann wird der Skriptname nicht übernommen.

```lua
if GetNameOfKeyInTable(Entities, _Object.Replacement) then
    Logic.InteractiveObjectSetReplacingEntityType(ID, _Object.Replacement);
end
```
Anstatt "Bordmittel" zu verweden - hier geht der Skriptname verloren - sollte stattdessen mit ReplaceEntity gearbeitet werden.

**Comment by Jelumar** [comment]
@totalwarANGEL1993 

Verstehe ich dich hier richtig, dass du vorschlägst hier den von dir zitierten Code zu entfernen und mit abschluss der Action dann ein ReplaceEntity auszuführen? (ModuleObjectInteraction.Global:OnObjectInteraction)

**Comment by totalwarANGEL1993** [comment]
Ja

**Comment by Jelumar** [comment]
Anpssung ist durchgeführt und kann in der aktuellen Beta Version (2.0) getestet werden

**Comment by Siedelwood** [comment]
Da es keine Beschwerden darüber gibt, schließen wir das hier und gehen davon aus, dass es jetzt funktioniert.
