### ISSUE TITLE
Tierzucht buggy mit Tieren bei falschen Gattern bzw falschen Territorien

### ISSUE THREAD

**Issue by Siedelwood** [Siedelwood/Revision#21]
**Describe the bug**
Die Tierzucht ist anfangs ausgeschaltet, erst ab dem Titel "Earl" (müsste Graf sein) gibt es die bei mir. Wenn man nun durch Platzmangel dann die fehlenden Gatter mit zugehörigem Produktionsgebäude auf dem anderen Terri baut, wird nichts gezüchtet. Erst, wenn man in dem Terri, wo das erste Produktionsgebäude gebaut wurde, die Kühe entlässt, sodass sie in die neuen Gatter laufen und dann im alten Terri wieder Gatter hinstellt, werden Kühe generiert. Gleiches gilt für die Schafe 

**To Reproduce**
1. Go into a map with delayed animal breeding
2. Build a cow/sheep farm in one territory
3. Build a farm in another territory
4. Breeding shouldn't work in these new territories

**Expected behavior**
ich drücke auf das Gatter, da erscheint ein Knopf und den drücke ich und es sollten Tiere vor genau diesem Gatter erscheinen

**Screenshots**
![github pic](https://github.com/user-attachments/assets/6d93123a-56d3-4ec3-bf67-bb74405b685f)

**Additional context**
im Gebiet (Weiß) Römerberg die Kühe und die Schafe hingebaut.  Da grenzt Heidelberg (grün) und Rheinau (Rosa) an. Irgendwann ist der Platz zu wenig in Römerberg und man muss ausweichen auf Heidelberg/Rheinau. Da funktioniert dann die Zucht nicht mehr. Wenn man jetzt da Gatter baut und die in Römerberg abreißt, sodass die Kühe dann in die Gatter von Heidelberg oder Rheinau laufen, und man dann wieder Gatter in Römerberg baut, dann wird in Römerberg mit der Viehzucht begonnen. Ansonsten wartet man bis zum Nimmerleinstag.

**Comment by Jelumar** [comment]
Won't fix, sieht derzeit so aus als wäre dies das gewünschte verhalten.

**Comment by Siedelwood** [comment]
Irgendwie ist es doch nicht so, wie es sein sollte. Hier: [Discord-Nachricht](https://discord.com/channels/850795541104427038/1314257840525017138/1314618269671362631)


Seitenfehler: Sollen die Zeilen so sein? Sollten das nicht () statt {} sein?
https://github.com/Siedelwood/QSB/blob/6104d5588544701e2dd7e54b8f6f1131c07d9d26/qsb/lua/modules/QSB_3_Lifestock/compatibility.lua#L46

https://github.com/Siedelwood/QSB/blob/6104d5588544701e2dd7e54b8f6f1131c07d9d26/qsb/lua/modules/QSB_3_Lifestock/compatibility.lua#L68

**Comment by Siedelwood** [comment]
Nochmal drüber geschaut und besprochen. Das Verhalten soll so sein. Vielleicht ist es nicht unbedingt klar, dass das nächste Gatter mit Plätzen in einer Reichweite von 4500 um das Gatter mit Kühen/Schafen zu setzen ist, aber vom Code her und der FUnktionsweiße soweit funktioniert alles.
