### ISSUE TITLE
Logikfehler bei Segment Quests

### ISSUE THREAD

**Issue by totalwarANGEL1993** [Siedelwood/Revision#22]
**Beschreibung**
Bei Segment Quests wird der Resulttyp "Ignore" im Code ignoriert (wie ironisch). Dadurch können Segment Quests stecken bleiben, wenn nicht alle ignorierten Segmente beendet werden.

**Fehler provozieren**
Schritte um den Fehler zu reproduzieren:
1. Einen Segment Quest mit mehreren Segmenten anlegen
2. Ein Segment das Resultat "Ignore" geben und als Goal z.B. Goal_NoChange einstellen
3. Segment Quest wird niemans beendet

**Comment by Jelumar** [comment]
Die Frage ist ob das ein Bug ist oder potentiell ein verhalten, das wir als korrekt bestimmen:
Wenn ich dich richtig verstehe bleibt hier das Ganze nur dann stecken wenn ein Quest auf Ignore nicht beendet wird. Das ist aber auch der Fall wenn ein Quest dessen Erfolg vorausgesetzt wird nicht beendet wird. Heißt ich versethe hier Ignore so, dass das Ergebnis der Quest ignoriert werden könnte, aber nicht die tatsache, dass Sie beendet werden sollte. Die Entscheidung des Spielers ist also egal, aber er muss sich entscheiden. Wenn etwas komplet egal ist und und nicht beendet werden muss, dann hätte es hier keinen Sinn das in den Segmented Quest reinzustecken.

@totalwarANGEL1993 gib mir gern Bescheid, falls ich das von dir beschriebene Verhalten falsch verstanden habe. Wenn es sich so verhällt wie ich das herauslese, kann es eigentlich so bleiben wie es ist würde ich sagen. Aber das können wir gerne auch nochmal besprechen was die Vor- und Nachteile davon sind und was jetzt am Ende besser ist.

**Comment by totalwarANGEL1993** [comment]
Ich habe das in meinem privaten Luftschloss bereits gefixt und das Verhalten geändert. Die Einstufung für die offizielle QSB überlasse ich den Verantwortlichen. Wenn du sagst, dass Verhalten wie es ist, ist für dich logisch nachvollziehbar und richtig so, dann ist das auch in Ordnung.

**Comment by Jelumar** [comment]
Bleibt nach interner Absprache erst mal so. Verhalten wird bis jetzt als logisch angesehen.
