### ISSUE TITLE
Horten von Waren hat falsches Bild bzw. geswapptes Bild, Tooltip fehlt

### ISSUE THREAD

**Issue by Siedelwood** [Siedelwood/Revision#24]
Der Knopf zum Halten von Waren in einem Gebäude ist vertauscht. Das durchgestrichene muss mit dem ohne den durchgestrichnen getauscht werden.
![grafik](https://github.com/user-attachments/assets/ac0cc490-fbc4-44c2-8bdc-170245b71ebf)
![grafik](https://github.com/user-attachments/assets/2344a211-c0a9-4f2e-b291-44fa14918c28)

Und der Tooltip fehlt

**Comment by Jelumar** [comment]
fixed
