### ISSUE TITLE
AP setzt Duration u.U. als Boolean

### ISSUE THREAD

**Issue by totalwarANGEL1993** [Siedelwood/Revision#26]
**Beschreibung**
Wenn die Dauer einer Seite nicht vorgegeben ist und anhand Textlänge berechnet werden soll, wird Duration als Boolean gesetzt und wird zu einem Fehler führen

**Ursache**
- briefingsystem/source.lua:224
```lua
_Page.Duration = (_Page.Duration < 6 and 6) or _Page.Duration < 6;
```
Das letzte `< 6` muss weg.

**Comment by Jelumar** [comment]
Ist nun gefixt durch den [Merge](https://github.com/Siedelwood/QSB/commit/70c2d8adeea619ddef04c86bf57f5cc14da9e87c)
