### ISSUE TITLE
Fehlende mögliche Attribute bei Briefings für mehr Gestaltung

### ISSUE THREAD

**Issue by Siedelwood** [Siedelwood/Revision#28]
Potentiell sind noch viele weitere Attribute in einem Briefingsystem möglich, die allerdings bei Briefing:AddPages nie übergeben werden.
Zu sehen in diesem [Issue ](https://github.com/Siedelwood/QSB/issues/25) + In dem Codecontext um die Zeilen herum.

**Comment by totalwarANGEL1993** [comment]
Und welche sollen das sein?

**Comment by schmeling65** [comment]
```lua
        return _Briefing:AddPage {
            Name            = Name,
            Title           = Title,
            Text            = Text,
            Action          = Action,
            Position        = Position,
            DisableSkipping = NoSkipping,
            DialogCamera    = DialogCam,
            Rotation        = Rotation,
            BigBars         = BigBars,
            Angle           = Angle,
            Zoom            = Zoom,
            FOV             = FOV,
            Duration        = Duration,
        };
        ```
        Das sind die bisher, die ich sehe.
        Da könnten vlt noch welche dazukommen.

**Comment by totalwarANGEL1993** [comment]
Du weißt schon, was der Sinn von ASP ist und wie es funktioniert? Die Funktion ist dafür da, schnell eine einfache Dialog Page zu erzeugen. Wer mehr will, kann AP benutzen. Na ja, soll @Jelumar entscheiden. Mir egal. 😏

**Comment by Jelumar** [comment]
Ist ein Missverständnis. Unterscheid zwischen AP uns APS war nicht bekannt.
