### ISSUE TITLE
API.CreateQuestDialog

### ISSUE THREAD

**Issue by Jelumar** [Siedelwood/Revision#5]
Fehlt in 3.0

**Comment by totalwarANGEL1993** [comment]
Das wurde durch das Dialog System ersetzt, was der alten Funktion nicht nur überlegen ist, sondern auch keinen Meldungsstau verursachen kann, weil es nicht die Voice Message Queue benutzt. Ich würde empfehlen, den alten Schinken wieder zu entfernen.

**Comment by Jelumar** [comment]
@totalwarANGEL1993 
Da dies hier aus Kompatibilitätsgründen zur 2.X gewünscht war wird das an der Stelle drin bleiben. Das mit dem Meldungsstau ist ja bekannt und wer diese Funktionen benutzt wird das Risiko auch kennen. Ich habe aber mal einen Hinweis in die Doku eingebaut in dem ich auf das Dialog System als neue und sicherere Alternative verweise.

**Comment by totalwarANGEL1993** [comment]
Es gäbe auch die Möglichkeit, die Funktion so umzuschreiben, dass sie einen Quest und einen zugehörigen Dialog erzeugt. Nicht so einfach, aber machbar.

**Comment by Jelumar** [comment]
Die Frage ist immer ob sich der Aufwand dazu lohnt.
