### ISSUE TITLE
Goal_Decide fehlt

### ISSUE THREAD

**Issue by Jelumar** [Siedelwood/Revision#6]
Behavior fehlt in der 3.0 und sollte aus der 2.x übernommen werden.

**Comment by totalwarANGEL1993** [comment]
Ich würde mir noch einmal überlegen, ob das Behavior in diesem Zustand verwendbar ist. ;)

**Comment by Jelumar** [comment]
@totalwarANGEL1993 
Danke für den Hinweis. Allerdings fehlt mir hier noch eine Info was genau das Problem ist.
Nachdem ich das in die 3.0 aufgenommen habe, wurde das Goal_Decide auch in einer Map benutzt und hat dort auch soweit ich das weiß funktioniert. Daher weiß ich nicht genau was du meinst. Gibt es ein Problem mit dem Behavior, das zu Problemen führen kann bzw nebenwirkungen hat? Oder übersehe ich hier etwas?

**Comment by totalwarANGEL1993** [comment]
@Jelumar 
Das Behavior hat folgende Probleme:
* Kann nicht in mehreren Quests verwendet werden
* Kann zu Störungen führen, wenn Requester auf andere Weise angezeigt werden
* Kann nicht im Multiplayer verwendet werden

**Comment by Jelumar** [comment]
Das sind tatsächlich relevante Informationen. Ist egal sofern in einer Singleplayer Map das nur einmal benutzt wird und keine andern Requester genutzt werden, aber trotzdem sollte das jeder auf dem Schirm haben, der es verwenden will. Aus gewünschten Kompatibilitätsgründen wird es vorerst in der QSB bleiben. Allerdings habe ich die von dir gennanten Probleme in der Doku hinterlegt und die Nutzung als "auf eigene Gefahr" markiert.
